name: DllBuild
on:
  push:
    branches:
      - master
      - 'issues/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Get source
      uses: actions/checkout@v2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest

    - name: Install build tools
      uses: awalsh128/cache-apt-pkgs-action@v1.1.0
      with:
        packages: make
        version: 1.0

    - name: Build
      run: make

    - name: Test
      run: make test
